apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-job-agent
  labels:
    app: schedule-job-agent
spec:
  selector:
    matchLabels:
      app: schedule-job-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: schedule-job-agent
    spec:
      containers:
        - name: schedule-job-agent
          image: sotaneum/schedule-job-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-job-agent-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: schedule-job-agent
